### ISSUE TITLE
[FEATURE REQUEST] separated posting buttons

### ISSUE THREAD

**Issue by conner-kent** [MasterSteelblade/WaterfallBugsFeatures#11]
**Motivation and Context**

**Is your feature request related to a problem? Please describe.**
Currently the posting buttons [post, draft, queue, reblog] are in a drop down menu. I think it would be more convenient if they were out of the drop down menu, and spaced out a little.

**Describe the feature/solution you'd like**
Can they be separated into a horizontal line instead, or as an option?

**Describe alternatives you've considered**
Alternatively I could just be more careful when posting. But I do lazy after queueing like 30 posts in a row. This might just be a me thing :v

**Is there a way to do this already?**
Uhh no! There's not. This is an option on tumblr though, via xkit.  Which is primarily what I'm inspired from. It's pretty convenient and really weird to go back to a drop down option. Idk, are other websites drop down only?

**Additional context**
This is what I mean:
![hiii](https://user-images.githubusercontent.com/75038244/102435002-beaec300-3fca-11eb-862c-032d085a8332.png)

**Comment by MasterSteelblade** [comment]
This is something that can't be done because of mobiles - there's not enough space to show all the buttons on there. In addition, people tend to complain about being overwhelmed when there's multiple buttons there, and posting immediately is the one that's wanted in 99% of cases, so this is going to be staying a dropdown.
